version: '3.8'

services:
  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
    environment:
      - RETENTION_TIME=15d

  alertmanager:
    build: ./alertmanager
    ports:
      - 9093:9093
    depends_on:
      - prometheus

  grafana:
    build: ./grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
