# Definindo a versão do docker compose
version: '3.8'

# Aqui vamos iniciar a definição dos serviços que basicamente são containers
# Para cada container podemos definir um network, volumes entre outras opções
services:
  # Prometheus container spec
  # Arqui vamos definir imagem, nome do container, rede, variáveis de ambiente e volumes
  # Existem outras configurações porém não irei utilizar para ficar o mais simples possível
  prometheus:
    image: lopes97/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    environment:
      - RETENTION_TIME=15d
    volumes:
      - prometheus_data:/etc/prometheus/data

  # Alertmanager container spec
  alertmanager:
    image: lopes97/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    depends_on:
      - prometheus

  # Grafana container spec
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

# Definindo os volumes utilizados para o prometheus e grafana
# Aqui estou definindo eles do tipo volume.
volumes:
  grafana_data: {}
  prometheus_data: {}