apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace: monitoramento
spec:
  # type: LoadBalancer
  selector:
    app: alertmanager
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
