apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace: monitoramento
spec:
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
