apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoramento
spec:
  # type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
